apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc-deployment
  labels:
    app: notification-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
        - name: notification-svc
          image: ahmedmq/notification-svc
          env:
            - name: ACCOUNT-SERVICE-URL
              value: http://account-svc:8080
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb-service:27017/notification
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 20


---

apiVersion: v1
kind: Service
metadata:
  name: notification-svc
spec:
  selector:
    app: notification-svc
  ports:
    - port: 8080
      targetPort: 8080