apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-svc-deployment
  labels:
    app: account-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-svc
  template:
    metadata:
      labels:
        app: account-svc
    spec:
      containers:
        - name: account-svc
          image: ahmedmq/account-svc
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-credentials
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: account-svc-config
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 20


---

apiVersion: v1
kind: Service
metadata:
  name: account-svc
spec:
  type: NodePort
  selector:
    app: account-svc
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080

